#!/usr/bin/env python3
"""Hello World Multi Linguas.

Dependendo da lingua configurada no ambiente o programa exibe a
correspondente.

Como usar:

Tenha a variável LANG devidamente configurada ex:

	export LANG=pt_BR

Execução

	puython3 hello.py
	ou
	./hello.py
"""
__version__ = "0.0.1"
__author__ = "Gliverson Almeida"
__license__ = "Unlicense"
#__ = dunder (double underline)

import os

current_language = os.getenv("LANG",)[:5]
# snake case = escrever em minusculo
# Pascal Case = escrever iniciando com maiusculo 
msg = "Hello, World!"

if current_language == "pt_BR":
	msg = "Olá, Mundo!"
elif current_language == "it_IT":
	msg = "Ciao, Mondo!"
elif current_language == "es_SP":
	msg = "Hola, Mundo!"
elif current_language == "fr_FR":
	msg = "Bonjour Monde"
		
print(msg)
# built-in 




